# Generated by Django 3.2.5 on 2021-12-02 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=70)),
                ('price', models.FloatField(default=5.0)),
                ('pieces', models.IntegerField(default=1)),
                ('instructions', models.CharField(max_length=80)),
                ('label', models.CharField(choices=[['BestSeller', 'BestSeller'], ['New', 'New'], ['Spicy', 'Spicy']], max_length=50)),
                ('label_color', models.CharField(choices=[['primary', 'primary'], ['secondary', 'secondary'], ['danger', 'danger'], ['warning', 'warning'], ['info', 'info']], max_length=50)),
                ('slug', models.SlugField(default='food_item')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[['Active', 'Active'], ['Delivered', 'Delivered']], max_length=50)),
                ('ordered_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
